export const globalStyle = {
    sizes: {
        xxSmall: 1,
        small: 3,
        medium: 6,
        large: 12,
        xLarge: 24
    },
    colours: {
        black: '#000000',
        lightBlack: '#212121',
        mediumBlack: '#000000B3',
        white: '#FFFFFF',
        darkWhite: '#EEEEEE',
        yellow: '#FFED00',
        darkGrey: '#666666',
        mediumGrey: '#00000033',
        lightGrey: '#D9D9D9',
        darkRed: '#D0011B',
        lightRed: '#FF6161',
        lightBlue: '#CEE0F5',
        lightYellow: '#FCF2BD',
        lightPurple:'#F5EBF9',
        lightPink: '#F9CFCF',
        lightGreen: '#DBF1C4',
        lighterPurple: '#d0bddb',
        lighterBlack: '#b1b1b1',
        blue: '#005FCC',
        lighterGrey: '#F8F8F8',
        red: '#D0011B',
        purple: '#6f2c91',
        darkBlue: '#006BF6',
        inherit: 'inherit',
        transparent: 'transparent',
    }
}
